# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HotpepperGourmetMcpServer < Formula
  desc ""
  homepage ""
  version "0.1.0-beta.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.4/hotpepper-gourmet-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "7cb909c486722a4c12ddb0ae836c7cb8727b7e590e3bc523ed1eccaf22ff305e"

      def install
        bin.install "hotpepper-gourmet-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.4/hotpepper-gourmet-mcp-server_Darwin_arm64.tar.gz"
      sha256 "8433b31e94ba867745e9441d234b438aac244a0eea430f5a4a65e6c9d19aa072"

      def install
        bin.install "hotpepper-gourmet-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.4/hotpepper-gourmet-mcp-server_Linux_x86_64.tar.gz"
        sha256 "2623c5218f1adf9115466a5240718e8306e90dfa8783dd747d16db13fc23fedb"

        def install
          bin.install "hotpepper-gourmet-mcp-server"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.4/hotpepper-gourmet-mcp-server_Linux_arm64.tar.gz"
        sha256 "6b1a474e8b23836ae4f7539868ee227994635483aa07266a419cfb5a222d13ec"

        def install
          bin.install "hotpepper-gourmet-mcp-server"
        end
      end
    end
  end
end
