# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HotpepperGourmetMcpServer < Formula
  desc ""
  homepage ""
  version "0.1.0-beta.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.9/hotpepper-gourmet-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "6cb37bed08ca4f680594f0d04691205414df7cb32a6435f3c3414546fdb4ac42"

      def install
        bin.install "hotpepper-gourmet-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.9/hotpepper-gourmet-mcp-server_Darwin_arm64.tar.gz"
      sha256 "4b6bd3601faab63f4f225cf0f79d67656a8dd13504fcbad9ef2e1b64ecb12115"

      def install
        bin.install "hotpepper-gourmet-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.9/hotpepper-gourmet-mcp-server_Linux_x86_64.tar.gz"
      sha256 "6af1150c4a128d532314d15bf83284497af9213b5d5c7bddd5ae3407213b5d22"
      def install
        bin.install "hotpepper-gourmet-mcp-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/hotpepper-gourmet-mcp-server/releases/download/v0.1.0-beta.9/hotpepper-gourmet-mcp-server_Linux_arm64.tar.gz"
      sha256 "c593a29e52e1be7132f5bcca0fd1297a99dfc864abcb820293b3993d0047a5b9"
      def install
        bin.install "hotpepper-gourmet-mcp-server"
      end
    end
  end
end
