# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nrdeco < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.2/nrdeco_Darwin_x86_64.tar.gz"
      sha256 "cb07afc8023db0cffdd2de67e706f4597b7135a6d322d82bb98614217cb876bc"

      def install
        bin.install "nrdeco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.2/nrdeco_Darwin_arm64.tar.gz"
      sha256 "e596e35386c9cb4c5f54aaa8f2c92a520541d2e7be139561c7605958888e2466"

      def install
        bin.install "nrdeco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.2/nrdeco_Linux_x86_64.tar.gz"
      sha256 "7cc284b184f4a643dc57c15ab4ae7e0e7366c80c14ece7734f9410bf869c3231"
      def install
        bin.install "nrdeco"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.2/nrdeco_Linux_arm64.tar.gz"
      sha256 "78b7fd2f67be3009c73926fc4992aa8842c67fe6c677915d552443cb6d225d60"
      def install
        bin.install "nrdeco"
      end
    end
  end
end
