# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nrdeco < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.0/nrdeco_Darwin_x86_64.tar.gz"
      sha256 "f7a13684ba59847c62cfcb3550187181609ed532708ad55d18e888b3de9536a7"

      def install
        bin.install "nrdeco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.0/nrdeco_Darwin_arm64.tar.gz"
      sha256 "ad4d95d32a09523f92cc852294f490900cf3eeda5a42ba302b45c6fe43d48a11"

      def install
        bin.install "nrdeco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.0/nrdeco_Linux_x86_64.tar.gz"
      sha256 "3eb4859638ec9293d9e3282b93230a0983a3108042cd204b0a463f83ffcdcc4f"
      def install
        bin.install "nrdeco"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/nrdeco/releases/download/v0.1.0/nrdeco_Linux_arm64.tar.gz"
      sha256 "9d7bd256e11f4bb6fe0882718e5439940357b92825a7c2058d30801345910d50"
      def install
        bin.install "nrdeco"
      end
    end
  end
end
