# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TagcaseAnalyzer < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase-analyzer_Darwin_x86_64.tar.gz"
      sha256 "896f069bea071b41333bc13c0215f4f73d7c48dbaa4edb126a02b6c27cce632b"

      def install
        bin.install "tagcase-analyzer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase-analyzer_Darwin_arm64.tar.gz"
      sha256 "9d9405b8fc00f0b9bb953decc3563067f2a4ea6098f91a9368f599a2e1abcbff"

      def install
        bin.install "tagcase-analyzer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase-analyzer_Linux_x86_64.tar.gz"
      sha256 "e8d8ea57cd60d74c992929a4194605dcfb75674abfdc72e013f3482b945e6350"
      def install
        bin.install "tagcase-analyzer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase-analyzer_Linux_arm64.tar.gz"
      sha256 "b3f756ff2013a756e3211bf9ace12ee71b08beba2000c016f702a69470b6aba4"
      def install
        bin.install "tagcase-analyzer"
      end
    end
  end
end
