# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tagcase < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase_Darwin_x86_64.tar.gz"
      sha256 "49529fd6d5d949dd5b53e2e1a58fbf2cd94786dc1c9ffc1158df31039a5b388a"

      def install
        bin.install "tagcase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase_Darwin_arm64.tar.gz"
      sha256 "dc9ef690a39f8f4f4197840bdeed910408225f3e67e2cf9f59fce7bccf1f3111"

      def install
        bin.install "tagcase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase_Linux_x86_64.tar.gz"
      sha256 "d1be0d5d29a2abeffa1d025b69101c8c3f992dfad8615d50155d32dbdce1f74a"
      def install
        bin.install "tagcase"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.1/tagcase_Linux_arm64.tar.gz"
      sha256 "a1ca24dcfeda927f99b2a2d67394e1e215ae15c946eaa3c694e345aae8bfc97a"
      def install
        bin.install "tagcase"
      end
    end
  end
end
