# This file was generated by GoReleaser. DO NOT EDIT.
cask "tagcase-analyzer" do
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tagcase-analyzer"

  on_macos do
    on_intel do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase-analyzer_Darwin_x86_64.tar.gz"
      sha256 "93b074038f5f967d25b3a8c8e1ca8f1f945c0cd1c85295d9cda1dc3d5f6a8f7a"
    end
    on_arm do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase-analyzer_Darwin_arm64.tar.gz"
      sha256 "80212e9137dc6ebad5a51d6a464970ddc03239e92fe99e9260ccd7cab5b1801c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase-analyzer_Linux_x86_64.tar.gz"
      sha256 "5da446db3978b51d9a70aab7011f3d2372eb0c35bd40bdbc4ef625b1453f1e7b"
    end
    on_arm do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase-analyzer_Linux_arm64.tar.gz"
      sha256 "04416d6cb3ea1fd743cfa0495db767cb172e65e2829caadac781443d34fcb900"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tagcase-analyzer"]
    end
  end

  # No zap stanza required
end
