# This file was generated by GoReleaser. DO NOT EDIT.
cask "tagcase" do
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tagcase"

  on_macos do
    on_intel do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase_Darwin_x86_64.tar.gz"
      sha256 "78eddb0914d717527837b2213c47c56528a8c2647f90d880c76c94de2c0d508d"
    end
    on_arm do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase_Darwin_arm64.tar.gz"
      sha256 "37e4145b3e20388a24ba5b742d8ecc53c6906268b35623fc26ca9c642bc1dae2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase_Linux_x86_64.tar.gz"
      sha256 "dd8c2973e49d45685ee132a61810d0d55bd1e9962b77b18b807da5589659751e"
    end
    on_arm do
      url "https://github.com/miyamo2/tagcase/releases/download/v0.1.0/tagcase_Linux_arm64.tar.gz"
      sha256 "15f8dfb635d4580c3f6ebf0cc67d7fa13041fd4caef4cd4af0a6b4586c713946"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tagcase"]
    end
  end

  # No zap stanza required
end
