# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Braider < Formula
  desc "A go vet analyzer that resolves DI bindings and generates wiring code automatically"
  homepage "https://github.com/miyamo2/braider"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.0/braider_0.1.0_darwin_amd64.tar.gz"
      sha256 "33f4ffeb53decdc4bc1335453c3f529a7ba0c232006e39fb7a5c861eecda3ddd"

      def install
        bin.install "braider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.0/braider_0.1.0_darwin_arm64.tar.gz"
      sha256 "9d7e7c36667454025f5d87a51a89e8b139c9384be21b708d00b9e2b094384cfe"

      def install
        bin.install "braider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.0/braider_0.1.0_linux_amd64.tar.gz"
      sha256 "0f1e32b4c6237d718487c577a63be5860c77680fbdd0ed092273d035d4c923a0"
      def install
        bin.install "braider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.0/braider_0.1.0_linux_arm64.tar.gz"
      sha256 "e7f117148591dd04a38de57b3a5ebd689e669feed02bf79fe3d088bdfe5b8fd5"
      def install
        bin.install "braider"
      end
    end
  end

  test do
    system "#{bin}/braider", "-h"
  end
end
