# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Braider < Formula
  desc "A go vet analyzer that resolves DI bindings and generates wiring code automatically"
  homepage "https://github.com/miyamo2/braider"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.2/braider_0.1.2_darwin_amd64.tar.gz"
      sha256 "63286c7cece143c7bb11e5d1a8c1673cdf54af758c7991643171d4f99d6d9d6f"

      define_method(:install) do
        bin.install "braider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.2/braider_0.1.2_darwin_arm64.tar.gz"
      sha256 "224e79f2fee677631cf52a7a809889db335d09b66f69c9d5c4cc957c33a9c9fb"

      define_method(:install) do
        bin.install "braider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.2/braider_0.1.2_linux_amd64.tar.gz"
      sha256 "ceec882682338e9f90d564b7d4dfc63eea52f621d3f5ce44e7678a398d539fe9"
      define_method(:install) do
        bin.install "braider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/braider/releases/download/v0.1.2/braider_0.1.2_linux_arm64.tar.gz"
      sha256 "6beaa183acf2d4214a9995bacffdaf1c6ee5d931c4a09a35a6351264f3e2b5e7"
      define_method(:install) do
        bin.install "braider"
      end
    end
  end

  test do
    system "#{bin}/braider", "-h"
  end
end
