# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Braider < Formula
  desc "A go vet analyzer that resolves DI bindings and generates wiring code automatically"
  homepage "https://github.com/miyamo2/braider"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miyamo2/braider/releases/download/v0.2.0/braider_0.2.0_darwin_amd64.tar.gz"
      sha256 "9a233f0f0d92e6ed71250c7dc786b3e6e6653ee2934a98f70b316ef42c7c1fc4"

      define_method(:install) do
        bin.install "braider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miyamo2/braider/releases/download/v0.2.0/braider_0.2.0_darwin_arm64.tar.gz"
      sha256 "56b6c140ef0c988d04d47fac91a67df47f994b8f648535ac69e0e008b128f058"

      define_method(:install) do
        bin.install "braider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/braider/releases/download/v0.2.0/braider_0.2.0_linux_amd64.tar.gz"
      sha256 "1dbf89da8ebb2afaf192243f2ef6531eaefff6c92a80facde36bbc5faab184d8"
      define_method(:install) do
        bin.install "braider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miyamo2/braider/releases/download/v0.2.0/braider_0.2.0_linux_arm64.tar.gz"
      sha256 "114f99155b37f295b0409f729819c9f1204338f011055265b35a08d76966423f"
      define_method(:install) do
        bin.install "braider"
      end
    end
  end

  test do
    system "#{bin}/braider", "-h"
  end
end
